# Generated by Django 4.1 on 2023-09-06 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=240, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='budget.account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit', to='budget.account')),
            ],
        ),
    ]
