# Generated by Django 4.1 on 2023-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='actual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
