# Generated by Django 4.1 on 2023-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_account_type_alter_budget_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
