# Generated by Django 4.1 on 2023-09-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budget_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onBalanceSheet',
            field=models.BooleanField(default=False),
        ),
    ]
