# Generated by Django 4.1 on 2023-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_account_onbalancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
