# Generated by Django 4.1 on 2023-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_budget_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
