# Generated by Django 4.1 on 2023-09-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_account_balance_alter_budget_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
