# Generated by Django 4.1 on 2023-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_budget_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=240)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saved', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
