# Generated by Django 4.1 on 2023-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_goal_alter_account_type_alter_budget_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
