# Generated by Django 4.1 on 2023-09-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_transaction_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='onBalanceSheet',
            new_name='inBankFeed',
        ),
    ]
