# Generated by Django 4.1 on 2023-10-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_rename_onbalancesheet_account_inbankfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='debit', to='budget.account'),
        ),
    ]
