# Generated by Django 4.1 on 2023-10-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_alter_budget_category_alter_transaction_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconcilliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconcilliation_date', models.DateField(auto_created=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.account')),
                ('transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='budget.transaction')),
            ],
        ),
    ]
