# Generated by Django 4.1 on 2023-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_rename_account_balance_reconcilliation_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconcilliation',
            name='reconcilliation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
