# Generated by Django 4.1 on 2023-10-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='available',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
