# Generated by Django 4.1 on 2023-10-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_alter_budget_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=10),
        ),
    ]
