# Generated by Django 4.1 on 2023-10-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
