# Generated by Django 4.1 on 2023-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_transaction_is_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reconciled_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
