# Generated by Django 4.1 on 2023-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_account_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaccounttype',
            old_name='name',
            new_name='sub_type',
        ),
    ]
