# Generated by Django 4.1 on 2023-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_rename_name_subaccounttype_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_type_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
