# Generated by Django 4.1 on 2023-10-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_alter_account_sub_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='num',
            field=models.IntegerField(unique=True),
        ),
    ]
