# Generated by Django 4.1 on 2023-10-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0032_alter_account_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sub_type_name',
        ),
    ]
