# Generated by Django 4.1 on 2023-11-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccounttype',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity'), ('Goal', 'Goal')], max_length=10),
        ),
    ]
