# Generated by Django 4.1 on 2023-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0036_monthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reconcilliation',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Reconcilliation',
        ),
    ]
